name: lobehub
services:
  lobe:
    image: crpi-dzjyl2rfnlfugj1m.cn-shanghai.personal.cr.aliyuncs.com/frogclaw/lobehub:latest
    container_name: lobehub
    ports:
      - '3210:3210'
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - 'KEY_VAULTS_SECRET=xJhL9PZ0RtBw4vVn8FmDq2QkKcY7sN5xWgTrEpHX6qA='
      - 'AUTH_SECRET=L9d1bK8mN5cVv7WxZq0XpFjR2nB6tYmH4vDcKxWgTrE='
      - 'APP_URL=https://frogclaw.chat'
      - 'DATABASE_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5200/lobechat'
      - 'S3_ENDPOINT=https://tos-s3-cn-beijing.volces.com'
      - 'S3_BUCKET=huanxing'
      - 'S3_ENABLE_PATH_STYLE=1'
      - 'LLM_VISION_IMAGE_USE_BASE64=1'
      - 'S3_SET_ACL=0'
      - 'SEARXNG_URL=http://searxng:8080'
      - 'REDIS_URL=redis://redis:6200'
      - 'REDIS_PREFIX=lobechat'
      - 'REDIS_TLS=0'
    restart: always
    networks:
      - lobe-network

  postgresql:
    image: paradedb/paradedb:latest-pg17
    container_name: lobe-postgres
    # Optional: Remove or change these ports if:
    # - You don't need external database access
    # - The ports conflict with other services on your host
    ports:
      - '5200:5200'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobechat'
      - 'POSTGRES_PASSWORD=uWNZugjBqixf8dxC'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5200']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network

  redis:
    image: redis:7-alpine
    container_name: lobe-redis
    # Optional: Remove or change these ports if:
    # - You don't need external access
    # - The ports conflict with other services on your host
    ports:
      - '6200:6200'
    command: redis-server --port 6200 --save 60 1000 --appendonly yes
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '6200', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    networks:
      - lobe-network

  searxng:
    image: searxng/searxng
    container_name: lobe-searxng
    volumes:
      - './searxng-settings.yml:/etc/searxng/settings.yml'
    environment:
      - 'SEARXNG_SETTINGS_FILE=/etc/searxng/settings.yml'
    restart: always
    networks:
      - lobe-network

networks:
  lobe-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
