/**
 * UsageNormalizer — translates provider-specific usage shapes into the
 * canonical `NormalizedUsage` structure that the billing domain consumes.
 *
 * The application middleware calls this AFTER the model response arrives.
 * The billing package never imports from agent-runtime or model-runtime.
 *
 * Token-class semantics
 * ─────────────────────
 *  prompt_token     – tokens in the context window sent to the model
 *  completion_token – tokens generated by the model
 *  total_token      – prompt + completion (convenience, not double-counted)
 *
 * Credit computation
 * ──────────────────
 *  credits = (tokens * creditsPerThousandTokens) / 1000n   (integer division)
 *
 * This keeps full integer semantics; no floating-point rounding errors.
 */
import { validateRequestId } from '../idempotency/keys';
import type { NormalizedUsage } from '../types/commands';
import type { UsagePriceSnapshot } from '../types/money';

// ─────────────────────────────────────────────────────────────────────────────
// Raw usage shapes (supplied by the application layer; vary by provider)
// ─────────────────────────────────────────────────────────────────────────────

/** Minimal usage shape that providers expose after a completion. */
export interface RawProviderUsage {
  /** Tokens in the completion. */
  completionTokens?: number;
  /** Tokens in the prompt / context. */
  promptTokens?: number;
  /** Some providers supply a pre-computed total. */
  totalTokens?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Normalization
// ─────────────────────────────────────────────────────────────────────────────

export class UsageNormalizer {
  /**
   * Converts a provider usage object into the canonical `NormalizedUsage`.
   *
   * Missing token counts default to 0 (conservative — no phantom charges).
   * `total_tokens` is recomputed from prompt + completion if the provider
   * did not supply it, to ensure internal consistency.
   *
   * @throws TypeError if `requestId` fails validation.
   */
  static normalize(params: {
    requestId: string;
    modelId: string;
    provider: string;
    raw: RawProviderUsage;
    durationMs?: number;
  }): NormalizedUsage {
    validateRequestId(params.requestId);

    const prompt = Math.max(0, Math.floor(params.raw.promptTokens ?? 0));
    const completion = Math.max(0, Math.floor(params.raw.completionTokens ?? 0));
    // Prefer provider-reported total; recompute if missing or inconsistent.
    const total =
      params.raw.totalTokens !== undefined
        ? Math.max(0, Math.floor(params.raw.totalTokens))
        : prompt + completion;

    return {
      requestId: params.requestId,
      modelId: params.modelId,
      provider: params.provider,
      promptTokens: prompt,
      completionTokens: completion,
      totalTokens: total,
      durationMs: params.durationMs,
    };
  }

  /**
   * Computes the credit cost for a normalized usage record given a price snapshot.
   *
   * Pricing strategy is determined by `snapshot.unitType`:
   *  - `prompt_token`     → charge on prompt tokens only
   *  - `completion_token` → charge on completion tokens only
   *  - `total_token`      → charge on total tokens
   *  - `request`          → flat per-request charge (snapshot.creditsPerUnit)
   *
   * `snapshot.creditsPerUnit` is interpreted as "credits per 1 000 tokens"
   * for token-based unit types, and "credits per request" for `request` type.
   *
   * Integer bigint division truncates toward zero (conservative).
   */
  static computeCredits(usage: NormalizedUsage, snapshot: UsagePriceSnapshot): bigint {
    switch (snapshot.unitType) {
      case 'prompt_token': {
        return (BigInt(usage.promptTokens) * snapshot.creditsPerUnit) / 1000n;
      }
      case 'completion_token': {
        return (BigInt(usage.completionTokens) * snapshot.creditsPerUnit) / 1000n;
      }
      case 'total_token': {
        return (BigInt(usage.totalTokens) * snapshot.creditsPerUnit) / 1000n;
      }
      case 'request': {
        return snapshot.creditsPerUnit;
      }
    }
  }

  /**
   * Builds a conservative upper-bound credit estimate given a token budget.
   *
   * Called BEFORE the provider responds (for the hold phase).
   * `maxTokens` is the request's configured completion limit.
   */
  static estimateCredits(
    params: { promptTokens: number; maxCompletionTokens: number },
    snapshot: UsagePriceSnapshot,
  ): bigint {
    const estimatedUsage: NormalizedUsage = {
      requestId: '_estimate',
      modelId: '',
      provider: '',
      promptTokens: params.promptTokens,
      completionTokens: params.maxCompletionTokens,
      totalTokens: params.promptTokens + params.maxCompletionTokens,
    };
    return UsageNormalizer.computeCredits(estimatedUsage, snapshot);
  }
}
